name: Build FastAPI Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4 # Checkout the repository content to github runner.
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 # Install the python version needed

      - name: Install dependencies
        run: |
          make install
      
      - name: Apply format with black
        run: |
          make format
      - name: Run test
        run: |
          make test

      - name: Apply Lint with pylint
        run: |
          make lint
      - name: Build container
        run: |
          make build
    
